In [1]:
!pip install corus

Requirement already satisfied: corus in /usr/local/lib/python3.11/dist-packages (0.10.0)

In [2]:
!wget https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz

--2025-03-11 15:54:49--  https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250311%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250311T155449Z&X-Amz-Expires=300&X-Amz-Signature=ab16c2059eb8500f23e0d8f2afc899c28e5f36448c13b37bd54e01cc6b94d120&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream [following]
--2025-03-11 15:54:49--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250311%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250311T155449Z&X-Amz-Expires=300&X-Amz-Signature=ab16c2059eb8500f23e0d8f2afc899c28e5f36448c13b37bd54e01cc6b94d120&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 527373240 (503M) [application/octet-stream]
Saving to: ‘lenta-ru-news.csv.gz.3’

lenta-ru-news.csv.g 100%[===================>] 502.94M   162MB/s    in 3.1s

2025-03-11 15:54:52 (162 MB/s) - ‘lenta-ru-news.csv.gz.3’ saved [527373240/527373240]

In [ ]:
import pandas as pd
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from tqdm import tqdm

In [4]:
from corus import load_lenta

path = 'lenta-ru-news.csv.gz'
records = load_lenta(path)
next(records)

LentaRecord(
    url='https://lenta.ru/news/2018/12/14/cancer/',
    title='Названы регионы России с\xa0самой высокой смертностью от\xa0рака',
    text='Вице-премьер по социальным вопросам Татьяна Голикова рассказала, в каких регионах России зафиксирована наиболее высокая смертность от рака, сообщает РИА Новости. По словам Голиковой, чаще всего онкологические заболевания становились причиной смерти в Псковской, Тверской, Тульской и Орловской областях, а также в Севастополе. Вице-премьер напомнила, что главные факторы смертности в России — рак и болезни системы кровообращения. В начале года стало известно, что смертность от онкологических заболеваний среди россиян снизилась впервые за три года. По данным Росстата, в 2017 году от рака умерли 289 тысяч человек. Это на 3,5 процента меньше, чем годом ранее.',
    topic='Россия',
    tags='Общество',
    date=None
)

In [6]:
articles = []
for i in range(100000):
  record = (next(records))
  arcicle = {'title': record.title.lower(), 'topic': record.topic.lower(),
             'text': record.text.lower()}
  articles.append(arcicle)

# Чтобы не было ошибок при разделении на train, test, validation
topic_counts = Counter(article['topic'] for article in articles)
articles = [article for article in articles if topic_counts[article['topic']] >= 4]

In [7]:
df = pd.DataFrame(articles).drop_duplicates().reset_index(drop=True)

In [8]:
df.head()

,title,topic,text
0,назван самый популярный российский телеканал 2...,интернет и сми,в 2016 году первый канал уступил первое место ...
1,музыкант исполнил песню из «титаника» ноздрями,культура,музыкант сайрус бхиладвала (cyrus bhiladvala) ...
2,преподаватель покончил с собой в аудитории пет...,россия,управление следственного комитета по санкт-пет...
3,в москве построят стеклянный автовокзал,дом,на месте здания автовокзала «щелковский» на во...
4,асад заявил о готовности обсуждать любые вопро...,мир,президент сирии башар асад заявил о готовности...

In [9]:
df.describe()

,title,topic,text
count,99997,99997,99997
unique,99867,19,99994
top,цб отозвал лицензии у двух московских банков,россия,крупнейшее за всю историю веерное исследование...
freq,8,15971,2

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
snowball = SnowballStemmer(language='russian')
stopWords = set(stopwords.words('russian'))

In [12]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [13]:
def preprocess(text):
    tokens = [token for token in word_tokenize(text, language="russian")]
    tokens = [token for token in tokens if token not in stopWords]
    tokens = [snowball.stem(token) for token in tokens]

    return ' '.join(tokens)

In [14]:
df['preprocessed_text'] = [preprocess(text) for text in tqdm(df.title +
                           '/n' + df.text, total=len(df))]

100%|██████████| 99997/99997 [15:41<00:00, 106.25it/s]

In [15]:
df.head()

,title,topic,text,preprocessed_text
0,назван самый популярный российский телеканал 2...,интернет и сми,в 2016 году первый канал уступил первое место ...,назва сам популярн российск телекана 2016 года...
1,музыкант исполнил песню из «титаника» ноздрями,культура,музыкант сайрус бхиладвала (cyrus bhiladvala) ...,музыкант исполн песн « титаник » ноздрями/нмуз...
2,преподаватель покончил с собой в аудитории пет...,россия,управление следственного комитета по санкт-пет...,преподавател поконч соб аудитор петербургск ву...
3,в москве построят стеклянный автовокзал,дом,на месте здания автовокзала «щелковский» на во...,москв постро стекля автовокзал/н мест здан авт...
4,асад заявил о готовности обсуждать любые вопро...,мир,президент сирии башар асад заявил о готовности...,асад заяв готовн обсужда люб вопрос оппозицией...

Пайплайн:
1.   Приводим заголовки и текст к нижнему регистру
2.   Объединяем заголовок с текcтом, добавив между ними символ переноса строки
3. Токенизируем
4. Убираем из списка токенов стоп-слова
5. Используем стеммер

Не используется лемматизация, т.к. стемминг быстрее, а информация о форме слов не сильно скажется на качестве классификации, т.к. все тексты написаны журналистами.

In [16]:
X_train, x_tt, y_train, y_tt = train_test_split(df['preprocessed_text'], df.topic, test_size=0.4, random_state=42, stratify=df.topic)
X_val, X_test, y_val, y_test = train_test_split(x_tt, y_tt, test_size=0.5, random_state=42, stratify=y_tt)

# Baseline

In [17]:
dummyClassifier = DummyClassifier(strategy="most_frequent")
dummyClassifier.fit(X_train, y_train)
y_dummy_pred = dummyClassifier.predict(X_val)

In [18]:
print(classification_report(y_val, y_dummy_pred, zero_division=0))

                   precision    recall  f1-score   support

                        0.00      0.00      0.00         3
   69-я параллель       0.00      0.00      0.00        91
           бизнес       0.00      0.00      0.00       959
      бывший ссср       0.00      0.00      0.00      1664
              дом       0.00      0.00      0.00       602
         из жизни       0.00      0.00      0.00       685
   интернет и сми       0.00      0.00      0.00      1134
             крым       0.00      0.00      0.00         1
    культпросвет        0.00      0.00      0.00         7
         культура       0.00      0.00      0.00      1205
          легпром       0.00      0.00      0.00        23
              мир       0.00      0.00      0.00      2927
  наука и техника       0.00      0.00      0.00      1198
      путешествия       0.00      0.00      0.00       634
           россия       0.16      1.00      0.28      3194
силовые структуры       0.00      0.00      0.00      1768
            спорт       0.00      0.00      0.00      1969
         ценности       0.00      0.00      0.00       657
        экономика       0.00      0.00      0.00      1278

         accuracy                           0.16     19999
        macro avg       0.01      0.05      0.01     19999
     weighted avg       0.03      0.16      0.04     19999

# Логистическая регрессия с TfidfVectorizer

In [19]:
tfidfVectorizer = TfidfVectorizer()

In [20]:
log_reg = LogisticRegression(random_state=42, max_iter=1000)
pipelineTfidf = Pipeline([('vectorizer', tfidfVectorizer), ('classifier', log_reg)])
pipelineTfidf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [21]:
y_tfidf_pred = pipelineTfidf.predict(X_val)

In [22]:
print(classification_report(y_val, y_tfidf_pred, zero_division=0))

                   precision    recall  f1-score   support

                        0.00      0.00      0.00         3
   69-я параллель       0.93      0.31      0.46        91
           бизнес       0.78      0.76      0.77       959
      бывший ссср       0.88      0.87      0.87      1664
              дом       0.86      0.72      0.79       602
         из жизни       0.76      0.59      0.66       685
   интернет и сми       0.80      0.72      0.76      1134
             крым       0.00      0.00      0.00         1
    культпросвет        0.00      0.00      0.00         7
         культура       0.85      0.88      0.87      1205
          легпром       0.83      0.22      0.34        23
              мир       0.81      0.90      0.86      2927
  наука и техника       0.91      0.92      0.91      1198
      путешествия       0.86      0.78      0.82       634
           россия       0.75      0.83      0.79      3194
силовые структуры       0.81      0.78      0.80      1768
            спорт       0.96      0.96      0.96      1969
         ценности       0.95      0.89      0.92       657
        экономика       0.89      0.87      0.88      1278

         accuracy                           0.84     19999
        macro avg       0.72      0.63      0.66     19999
     weighted avg       0.84      0.84      0.84     19999

# Логистическая регрессия с CountVectorizer

In [23]:
countVectorizer = CountVectorizer()

In [24]:
pipelineCount = Pipeline([('vectorizer', countVectorizer), ('classifier', log_reg)])
pipelineCount.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [25]:
y_count_pred = pipelineCount.predict(X_val)
print(classification_report(y_val, y_count_pred, zero_division=0))

                   precision    recall  f1-score   support

                        0.00      0.00      0.00         3
   69-я параллель       0.89      0.69      0.78        91
           бизнес       0.77      0.75      0.76       959
      бывший ссср       0.89      0.87      0.88      1664
              дом       0.87      0.79      0.83       602
         из жизни       0.72      0.62      0.67       685
   интернет и сми       0.77      0.74      0.76      1134
             крым       0.00      0.00      0.00         1
    культпросвет        0.00      0.00      0.00         7
         культура       0.87      0.87      0.87      1205
          легпром       0.88      0.61      0.72        23
              мир       0.84      0.88      0.86      2927
  наука и техника       0.91      0.92      0.92      1198
      путешествия       0.85      0.83      0.84       634
           россия       0.77      0.81      0.79      3194
силовые структуры       0.79      0.78      0.78      1768
            спорт       0.97      0.96      0.97      1969
         ценности       0.94      0.93      0.93       657
        экономика       0.88      0.87      0.88      1278

         accuracy                           0.84     19999
        macro avg       0.71      0.68      0.70     19999
     weighted avg       0.84      0.84      0.84     19999

# Подбор гиперпараметров

### TfidfVectorizer

### CountVectorizer