In [3]:
!pip install corus

Requirement already satisfied: corus in /usr/local/lib/python3.11/dist-packages (0.10.0)

In [4]:
!wget https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz

--2025-06-13 07:38:25--  https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250613%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250613T073825Z&X-Amz-Expires=300&X-Amz-Signature=fc2b3cb820bbd123f4cbfa5e11d20ba3a4bf682fd85f96f2bdce2919ed93f7b9&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream [following]
--2025-06-13 07:38:25--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250613%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250613T073825Z&X-Amz-Expires=300&X-Amz-Signature=fc2b3cb820bbd123f4cbfa5e11d20ba3a4bf682fd85f96f2bdce2919ed93f7b9&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 527373240 (503M) [application/octet-stream]
Saving to: ‘lenta-ru-news.csv.gz.2’

lenta-ru-news.csv.g 100%[===================>] 502.94M   114MB/s    in 3.9s

2025-06-13 07:38:29 (129 MB/s) - ‘lenta-ru-news.csv.gz.2’ saved [527373240/527373240]

In [5]:
import pandas as pd
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

from tqdm import tqdm

In [6]:
from corus import load_lenta

path = 'lenta-ru-news.csv.gz'
records = load_lenta(path)
next(records)

LentaRecord(
    url='https://lenta.ru/news/2018/12/14/cancer/',
    title='Названы регионы России с\xa0самой высокой смертностью от\xa0рака',
    text='Вице-премьер по социальным вопросам Татьяна Голикова рассказала, в каких регионах России зафиксирована наиболее высокая смертность от рака, сообщает РИА Новости. По словам Голиковой, чаще всего онкологические заболевания становились причиной смерти в Псковской, Тверской, Тульской и Орловской областях, а также в Севастополе. Вице-премьер напомнила, что главные факторы смертности в России — рак и болезни системы кровообращения. В начале года стало известно, что смертность от онкологических заболеваний среди россиян снизилась впервые за три года. По данным Росстата, в 2017 году от рака умерли 289 тысяч человек. Это на 3,5 процента меньше, чем годом ранее.',
    topic='Россия',
    tags='Общество',
    date=None
)

In [7]:
articles = []
for i in range(100000):
  record = (next(records))
  arcicle = {'title': record.title.lower(), 'topic': record.topic.lower(),
             'text': record.text.lower()}
  articles.append(arcicle)

# Чтобы не было ошибок при разделении на train, test, validation
topic_counts = Counter(article['topic'] for article in articles)
articles = [article for article in articles if topic_counts[article['topic']] >= 4]

In [8]:
df = pd.DataFrame(articles).drop_duplicates().reset_index(drop=True)

In [9]:
df.head()

,title,topic,text
0,австрия не представила доказательств вины росс...,спорт,австрийские правоохранительные органы не предс...
1,в сша раскрыли сумму расходов на расследование...,мир,с начала расследования российского вмешательст...
2,хакеры рассказали о планах великобритании зами...,мир,хакерская группировка anonymous опубликовала н...
3,архиепископ канонической упц отказался прийти ...,бывший ссср,архиепископ канонической украинской православн...
4,российскую молодежь предложили обучать духовны...,интернет и сми,российская молодежь лучше усвоит духовные ценн...

In [10]:
df.describe()

,title,topic,text
count,94,94,94
unique,94,10,94
top,австрия не представила доказательств вины росс...,мир,австрийские правоохранительные органы не предс...
freq,1,19,1

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
snowball = SnowballStemmer(language='russian')
stopWords = set(stopwords.words('russian'))

In [13]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
def preprocess(text):
    tokens = [token for token in word_tokenize(text, language="russian")]
    tokens = [token for token in tokens if token not in stopWords]
    tokens = [snowball.stem(token) for token in tokens]

    return ' '.join(tokens)

In [15]:
df['preprocessed_text'] = [preprocess(text) for text in tqdm(df.title +
                           '/n' + df.text, total=len(df))]

100%|██████████| 94/94 [00:01<00:00, 58.10it/s]

In [16]:
df.head()

,title,topic,text,preprocessed_text
0,австрия не представила доказательств вины росс...,спорт,австрийские правоохранительные органы не предс...,австр представ доказательств вин российск биат...
1,в сша раскрыли сумму расходов на расследование...,мир,с начала расследования российского вмешательст...,сша раскр сумм расход расследован « российск д...
2,хакеры рассказали о планах великобритании зами...,мир,хакерская группировка anonymous опубликовала н...,хакер рассказа план великобритан заминирова се...
3,архиепископ канонической упц отказался прийти ...,бывший ссср,архиепископ канонической украинской православн...,архиепископ каноническ упц отказа прийт « сата...
4,российскую молодежь предложили обучать духовны...,интернет и сми,российская молодежь лучше усвоит духовные ценн...,российск молодеж предлож обуча духовн ценност ...

Пайплайн:
1.   Приводим заголовки и текст к нижнему регистру
2.   Объединяем заголовок с тектом, добавив между ними символ переноса строки
3. Токенизируем
4. Убираем из списка токенов стоп-слова
5. Используем стеммер

Не используется лемматизация, т.к. стемминг быстрее, а информация о форме слов не сильно скажется на качестве классификации, т.к. все тексты написаны журналистами.

In [17]:
X_train, x_tt, y_train, y_tt = train_test_split(df['preprocessed_text'], df.topic, test_size=0.4, random_state=42, stratify=df.topic)
X_val, X_test, y_val, y_test = train_test_split(x_tt, y_tt, test_size=0.5, random_state=42, stratify=y_tt)

# Baseline

In [18]:
dummyClassifier = DummyClassifier(strategy="most_frequent")
dummyClassifier.fit(X_train, y_train)
y_dummy_pred = dummyClassifier.predict(X_val)

In [19]:
print(classification_report(y_val, y_dummy_pred, zero_division=0))

                 precision    recall  f1-score   support

    бывший ссср       0.00      0.00      0.00         2
            дом       0.00      0.00      0.00         1
       из жизни       0.00      0.00      0.00         1
 интернет и сми       0.00      0.00      0.00         1
       культура       0.00      0.00      0.00         1
            мир       0.21      1.00      0.35         4
наука и техника       0.00      0.00      0.00         1
         россия       0.00      0.00      0.00         2
          спорт       0.00      0.00      0.00         3
      экономика       0.00      0.00      0.00         3

       accuracy                           0.21        19
      macro avg       0.02      0.10      0.03        19
   weighted avg       0.04      0.21      0.07        19

# Логистическая регрессия с TfidfVectorizer

In [20]:
tfidfVectorizer = TfidfVectorizer()

In [21]:
log_reg = LogisticRegression(random_state=42, max_iter=1000)
pipelineTfidf = Pipeline([('vectorizer', tfidfVectorizer), ('classifier', log_reg)])
pipelineTfidf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [22]:
y_tfidf_pred = pipelineTfidf.predict(X_val)

In [23]:
print(classification_report(y_val, y_tfidf_pred, zero_division=0))

                 precision    recall  f1-score   support

    бывший ссср       1.00      0.50      0.67         2
            дом       0.00      0.00      0.00         1
       из жизни       0.00      0.00      0.00         1
 интернет и сми       0.00      0.00      0.00         1
       культура       0.00      0.00      0.00         1
            мир       0.27      1.00      0.42         4
наука и техника       0.00      0.00      0.00         1
         россия       0.00      0.00      0.00         2
          спорт       1.00      1.00      1.00         3
      экономика       0.00      0.00      0.00         3

       accuracy                           0.42        19
      macro avg       0.23      0.25      0.21        19
   weighted avg       0.32      0.42      0.32        19

# Логистическая регрессия с CountVectorizer

In [24]:
countVectorizer = CountVectorizer()

In [25]:
pipelineCount = Pipeline([('vectorizer', countVectorizer), ('classifier', log_reg)])
pipelineCount.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [26]:
y_count_pred = pipelineCount.predict(X_val)
print(classification_report(y_val, y_count_pred, zero_division=0))

                 precision    recall  f1-score   support

    бывший ссср       1.00      0.50      0.67         2
            дом       0.00      0.00      0.00         1
       из жизни       0.00      0.00      0.00         1
 интернет и сми       0.00      0.00      0.00         1
       культура       0.00      0.00      0.00         1
            мир       0.33      0.25      0.29         4
наука и техника       0.00      0.00      0.00         1
         россия       0.00      0.00      0.00         2
          спорт       0.27      1.00      0.43         3
      экономика       0.50      0.33      0.40         3

       accuracy                           0.32        19
      macro avg       0.21      0.21      0.18        19
   weighted avg       0.30      0.32      0.26        19

# Подбор гиперпараметров

### TfidfVectorizer

In [27]:
parameters = {
    "vectorizer__min_df": [1, 3, 5],
    'vectorizer__max_df': (0.5, 0.75, 1.0),
    'vectorizer__ngram_range': [(1, 1), (1, 2)],
    'classifier__C': (0.1, 1, 10),
}

grid_search_tfidf = GridSearchCV(pipelineTfidf, parameters, cv=3, scoring="accuracy")
grid_search_tfidf.fit(X_train, y_train)
print(f"Best parameters: {grid_search_tfidf.best_params_}")
print(f"Best score: {grid_search_tfidf.best_score_}")

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(

Best parameters: {'classifier__C': 10, 'vectorizer__max_df': 0.5, 'vectorizer__min_df': 1, 'vectorizer__ngram_range': (1, 2)}
Best score: 0.48148148148148145

In [28]:
best_model_tfidf = grid_search_tfidf.best_estimator_
y_pred_test_tfidf = best_model_tfidf.predict(X_test)

In [29]:
print(classification_report(y_test, y_pred_test_tfidf, zero_division=0))

                 precision    recall  f1-score   support

    бывший ссср       1.00      1.00      1.00         2
            дом       0.00      0.00      0.00         1
       из жизни       0.00      0.00      0.00         1
 интернет и сми       0.00      0.00      0.00         1
       культура       0.00      0.00      0.00         1
            мир       0.36      1.00      0.53         4
наука и техника       0.00      0.00      0.00         1
         россия       0.00      0.00      0.00         3
          спорт       0.75      1.00      0.86         3
      экономика       0.50      0.50      0.50         2

       accuracy                           0.53        19
      macro avg       0.26      0.35      0.29        19
   weighted avg       0.35      0.53      0.41        19

### CountVectorizer

In [30]:
grid_search_count = GridSearchCV(pipelineTfidf, parameters, cv=3, scoring="accuracy")
grid_search_count.fit(X_train, y_train)
print(f"Best parameters: {grid_search_count.best_params_}")
print(f"Best score: {grid_search_count.best_score_}")

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(

Best parameters: {'classifier__C': 10, 'vectorizer__max_df': 0.5, 'vectorizer__min_df': 1, 'vectorizer__ngram_range': (1, 2)}
Best score: 0.48148148148148145

In [31]:
best_model_count = grid_search_count.best_estimator_
y_pred_test_count = best_model_count.predict(X_test)

In [32]:
print(classification_report(y_test, y_pred_test_count, zero_division=0))

                 precision    recall  f1-score   support

    бывший ссср       1.00      1.00      1.00         2
            дом       0.00      0.00      0.00         1
       из жизни       0.00      0.00      0.00         1
 интернет и сми       0.00      0.00      0.00         1
       культура       0.00      0.00      0.00         1
            мир       0.36      1.00      0.53         4
наука и техника       0.00      0.00      0.00         1
         россия       0.00      0.00      0.00         3
          спорт       0.75      1.00      0.86         3
      экономика       0.50      0.50      0.50         2

       accuracy                           0.53        19
      macro avg       0.26      0.35      0.29        19
   weighted avg       0.35      0.53      0.41        19